language: bash
sudo: required
script:  BRANCH_NUMBER=`echo -n "${TRAVIS_BRANCH}" | sed -e 's/\.//g'` && if [ ${BRANCH_NUMBER} -eq "270" ] ; then export PROJECTBRANCH="${TRAVIS_BRANCH}" && ./install.sh -a ; elif [ ${BRANCH_NUMBER} -ge "260" ] ; then ./install.sh -a -b ${TRAVIS_BRANCH} ; else echo "Automated build testing only supported in version 2.6.0 or above" && true ; fi
