language: bash
sudo: required
script:  CONFIG="example.config" && BRANCH_NUMBER=`echo -n "${TRAVIS_BRANCH}" | sed -e 's/\.//g'` && if [ "${BRANCH_NUMBER}" -ge "260" ] ; then ./install.sh -a -b "${TRAVIS_BRANCH}" -c "${CONFIG}" ; else echo "Automated build testing only supported in version 2.6.0 or above, but returning true for consistency" && true ; fi
