language: bash
sudo: required
script:  BRANCH_NUMBER=`echo -n "${TRAVIS_BRANCH}" | sed -e 's/\.//g'` && if [ ${BRANCH_NUMBER} -eq "270" ] ; then export PROJECTBRANCH="${TRAVIS_BRANCH}" -a && ./install.sh ; elif [ ${BRANCH_NUMBER} -ge "60" ] ; then ./install.sh -a -b ${TRAVIS_BRANCH} ; else ./install.sh ; fi
