language: 	bash

sudo: 		required

before_install: sudo apt-get -qq update && sudo apt-get -qq install -y cmake libcurl4-openssl-dev libdw-dev libelf-dev kcov

install: 	true

script:  	mkdir -p coverage && BRANCH_NUMBER=`echo -n "${TRAVIS_BRANCH}" | sed -e 's/\.//g'` && if [[ "${BRANCH_NUMBER}" -eq "270" ]] ; then export PROJECTBRANCH="${TRAVIS_BRANCH}" ; kcov coverage ./install.sh -a ; true ; elif [[ "${BRANCH_NUMBER}" -ge "260" ]] ; then kcov coverage ./install.sh -a -b ${TRAVIS_BRANCH} ; else echo "Automated build testing only supported in version 2.6.0 or above." ; fi

after_success:  bash <(curl -s https://codecov.io/bash) -s coverage || echo "Codecov did not collect coverage reports"
