language: bash
sudo: required
script:  if [ "${TRAVIS_BRANCH}" = "2.6.0" ]; then ./install.sh -a -b ${TRAVIS_BRANCH} ; elif [ "${TRAVIS_BRANCH}" = "2.7.0" ]; then export PROJECTBRANCH="${TRAVIS_BRANCH}" && ./install.sh ; else ./install.sh ; fi
